import {rand,lerp,smoothstep} from './utils.js';
export const terrain={heightmap:[],foliage:[],soilMaskCanvas:null,soilMaskCtx:null,W:0,H:0};
function generateCurve(count,baseline,amp){const pts=new Array(count);let p=rand()*1000;for(let i=0;i<count;i++){p+=0.25;const r=Math.sin(p*0.23)+Math.cos(p*0.11)*0.5+Math.sin(p*0.07)*0.33;pts[i]=baseline+amp*r;}return pts;}
function resampleCurve(curve){const n=curve.length;const out=new Array(terrain.W);for(let x=0;x<terrain.W;x++){const t=x*(n-1)/(terrain.W-1);const i=Math.floor(t);const f=t-i;const a=curve[i];const b=curve[Math.min(i+1,n-1)];out[x]=lerp(a,b,smoothstep(f));}return out;}
export function setupTerrain(W,H){terrain.W=W;terrain.H=H;terrain.soilMaskCanvas=document.createElement('canvas');terrain.soilMaskCanvas.width=W;terrain.soilMaskCanvas.height=H;terrain.soilMaskCtx=terrain.soilMaskCanvas.getContext('2d');}
export function generateTerrain(){const base=terrain.H*0.5;const amp=terrain.H*0.12;terrain.heightmap=resampleCurve(generateCurve(120,base,amp));const thickness=terrain.H*0.12;let p=rand()*1000;terrain.foliage=new Array(terrain.W);for(let x=0;x<terrain.W;x++){p+=0.25;const j=Math.sin(p*0.23)*terrain.H*0.02+Math.cos(p*0.17)*terrain.H*0.015;terrain.foliage[x]=terrain.heightmap[x]-thickness+j;}const c=terrain.soilMaskCtx;c.clearRect(0,0,terrain.W,terrain.H);c.fillStyle="#5a3a2e";c.beginPath();c.moveTo(0,terrain.H);for(let x=0;x<terrain.W;x++)c.lineTo(x,terrain.heightmap[x]);c.lineTo(terrain.W,terrain.H);c.closePath();c.fill();}
export function groundYAt(x){const xi=Math.max(0,Math.min(terrain.W-1,Math.floor(x)));return terrain.heightmap[xi];}
export function drawSoil(ctx){ctx.drawImage(terrain.soilMaskCanvas,0,0);}
export function drawSky(ctx){const g=ctx.createLinearGradient(0,0,0,terrain.H);g.addColorStop(0,'#87cefa');g.addColorStop(0.5,'#69aef2');g.addColorStop(1,'#3c78d8');ctx.fillStyle=g;ctx.fillRect(0,0,terrain.W,terrain.H);}
export function drawFoliage(ctx){const top=Math.min(...terrain.foliage);const bottom=Math.max(...terrain.heightmap);const g=ctx.createLinearGradient(0,top,0,bottom);g.addColorStop(0,'rgba(46,139,87,0.0)');g.addColorStop(1,'#2e8b57');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,terrain.heightmap[0]);for(let x=1;x<terrain.W;x++)ctx.lineTo(x,terrain.heightmap[x]);for(let x=terrain.W-1;x>=0;x--)ctx.lineTo(x,terrain.foliage[x]);ctx.closePath();ctx.fill();}
export function digCircle(x,y,r){const c=terrain.soilMaskCtx;c.globalCompositeOperation='destination-out';c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();c.globalCompositeOperation='source-over';}
export function alphaAt(x,y){const xi=Math.floor(x);const yi=Math.floor(y);if(xi<0||yi<0||xi>=terrain.W||yi>=terrain.H)return 0;const d=terrain.soilMaskCtx.getImageData(xi,yi,1,1).data;return d[3];}
export function isSolid(x,y){return alphaAt(x,y)>10;}
